name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      ## Test
      - name: Run tests
        run: yarn test:ci

      - name: Upload artifacts on fail
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: videos
          path: tests/e2e/videos/
