name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1

      ## Test
      - name: Run component tests
        run: yarn test

      # - name: Start Vite devserver
      #   run: yarn start

      # - name: Run tests
      #   run: yarn test:ci

      - name: Upload artifacts on fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: tests/e2e/videos/
